// fsr_rcas_ps.h -- compiled pixel shader bytecode for Phase B of the
// visual-enhancement suite plan (approved plan,
// C:\Users\kyesa\.claude\plans\twinkly-tickling-gem.md): FSR 1.0 RCAS (Robust
// Contrast Adaptive Sharpening), the first real full-screen effect built on top
// of Phase A's capture/composite pipeline (DrawFullScreenPass, overlay_hud.cpp).
//
// Compiled OFFLINE via the Windows SDK's fxc.exe from
// re_notes/shaders/fsr_rcas.hlsl (source, and the full port-fidelity/licensing
// notes, kept in re_notes/ for the record, not part of the build) -- embedded
// directly as a byte array, exactly like this project's existing
// options_blur_ps.h/fullscreen_passthrough_ps.h. No runtime shader-compiler
// dependency.
//
// ps_3_0, NOT this project's usual ps_2_0 -- tried ps_2_0 first (matching
// convention) and it genuinely does not fit: fxc reports 74 arithmetic
// instruction slots needed, ps_2_0's real hard cap is 64
// ("error X5608: ... Max. allowed by the target (ps_2_0) is 64"). RCAS's real
// per-pixel math (5-tap neighborhood, min/max ring, noise detection, an exact
// contrast-clip solve) is simply bigger than the existing 9-tap blur/passthrough
// shaders. ps_3_0 is safe on this project's real target hardware (confirmed live,
// an NVIDIA RTX 2080 Ti, native SM3+ for well over a decade) -- per the
// visual-suite plan's own Phase B text ("check real device pixel-shader-version
// caps (GetDeviceCaps) before committing to which"), EnsureRcasShader
// (overlay_hud.cpp) checks the real device's PixelShaderVersion cap before
// attempting to load this and refuses gracefully (falls back to no sharpening)
// on hardware below SM3, rather than assuming.
#pragma once

#if 0
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 sharpness;
//   sampler2D tex0;
//   float4 texelSize;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   texelSize    c0       1
//   sharpness    c1       1
//   tex0         s0       1
//

    ps_3_0
    def c2, 0, -1, 1, 0.5
    def c3, 4, -4, -0.1875, 1
    def c4, 0.25, -9.99999997e-007, 1000000, 4
    dcl_texcoord v0.xy
    dcl_2d s0
    mov r0.xyz, c2
    mad r1, c0.yyxy, r0.xyyx, v0.xyxy
    texld r2, r1, s0
    texld r1, r1.zwzw, s0
    mad r0.y, r2.x, c2.w, r2.y
    mad r0.y, r2.z, c2.w, r0.y
    mad r0.w, r1.x, c2.w, r1.y
    mad r0.w, r1.z, c2.w, r0.w
    max r1.w, r0.y, r0.w
    mad r3, c0.xyyy, r0.zxxz, v0.xyxy
    texld r4, r3, s0
    texld r3, r3.zwzw, s0
    mad r0.x, r4.x, c2.w, r4.y
    mad r0.x, r4.z, c2.w, r0.x
    texld r5, v0, s0
    mad r0.z, r5.x, c2.w, r5.y
    mad r0.z, r5.z, c2.w, r0.z
    max r2.w, r0.z, r0.x
    max r3.w, r1.w, r2.w
    mad r1.w, r3.x, c2.w, r3.y
    mad r1.w, r3.z, c2.w, r1.w
    max r2.w, r3.w, r1.w
    min r3.w, r0.w, r0.y
    mul r0.w, r0.w, c4.x
    mad r0.y, r0.y, c4.x, r0.w
    mad r0.y, r0.x, c4.x, r0.y
    min r4.w, r0.x, r0.z
    min r0.x, r4.w, r3.w
    min r3.w, r1.w, r0.x
    mad r0.x, r1.w, c4.x, r0.y
    add r0.x, -r0.z, r0.x
    add r0.y, r2.w, -r3.w
    add r0.z, r0.y, c4.y
    rcp r0.y, r0.y
    cmp r0.y, r0.z, r0.y, c4.z
    mul_sat r0.x, r0.y, r0_abs.x
    mad r0.x, r0.x, -c2.w, -c2.y
    min r0.yzw, r1.xxyz, r2.xxyz
    min r6.xyz, r3, r4
    min r7.xyz, r6, r0.yzww
    min r0.yzw, r5.xxyz, r7.xxyz
    mad r6.xyz, r7, c3.x, c3.y
    max r7.xyz, r2, r1
    add r1.xyz, r1, r2
    add r1.xyz, r3, r1
    max r2.xyz, r4, r3
    add r1.xyz, r4, r1
    max r3.xyz, r7, r2
    mul r2.xyz, r3, c4.w
    max r4.xyz, r3, r5
    add r3.xyz, -r4, c2.z
    rcp r4.x, r2.x
    rcp r4.y, r2.y
    rcp r4.z, r2.z
    mul r0.yzw, r0, r4.xxyz
    rcp r2.x, r6.x
    rcp r2.y, r6.y
    rcp r2.z, r6.z
    mul r2.xyz, r2, r3
    max r3.xyz, -r0.yzww, r2
    max r0.y, r3.x, r3.y
    max r1.w, r0.y, r3.z
    min r0.y, r1.w, c2.x
    max r1.w, c3.z, r0.y
    mul r0.y, r1.w, c1.x
    mul r0.x, r0.x, r0.y
    mad r0.yzw, r0.x, r1.xxyz, r5.xxyz
    mad r0.x, r0.x, c3.x, c3.w
    rcp r0.x, r0.x
    mul oC0.xyz, r0.x, r0.yzww
    mov oC0.w, c2.z

// approximately 71 instruction slots used (5 texture, 66 arithmetic)
#endif

const BYTE g_fsrRcasPixelShaderBytecode[] =
{
      0,   3, 255, 255, 254, 255,
     51,   0,  67,  84,  65,  66,
     28,   0,   0,   0, 157,   0,
      0,   0,   0,   3, 255, 255,
      3,   0,   0,   0,  28,   0,
      0,   0,   0,   1,   0,   0,
    150,   0,   0,   0,  88,   0,
      0,   0,   2,   0,   1,   0,
      1,   0,   6,   0, 100,   0,
      0,   0,   0,   0,   0,   0,
    116,   0,   0,   0,   3,   0,
      0,   0,   1,   0,   2,   0,
    124,   0,   0,   0,   0,   0,
      0,   0, 140,   0,   0,   0,
      2,   0,   0,   0,   1,   0,
      2,   0, 100,   0,   0,   0,
      0,   0,   0,   0, 115, 104,
     97, 114, 112, 110, 101, 115,
    115,   0, 171, 171,   1,   0,
      3,   0,   1,   0,   4,   0,
      1,   0,   0,   0,   0,   0,
      0,   0, 116, 101, 120,  48,
      0, 171, 171, 171,   4,   0,
     12,   0,   1,   0,   1,   0,
      1,   0,   0,   0,   0,   0,
      0,   0, 116, 101, 120, 101,
    108,  83, 105, 122, 101,   0,
    112, 115,  95,  51,  95,  48,
      0,  77, 105,  99, 114, 111,
    115, 111, 102, 116,  32,  40,
     82,  41,  32,  72,  76,  83,
     76,  32,  83, 104,  97, 100,
    101, 114,  32,  67, 111, 109,
    112, 105, 108, 101, 114,  32,
     49,  48,  46,  49,   0, 171,
    171, 171,  81,   0,   0,   5,
      2,   0,  15, 160,   0,   0,
      0,   0,   0,   0, 128, 191,
      0,   0, 128,  63,   0,   0,
      0,  63,  81,   0,   0,   5,
      3,   0,  15, 160,   0,   0,
    128,  64,   0,   0, 128, 192,
      0,   0,  64, 190,   0,   0,
    128,  63,  81,   0,   0,   5,
      4,   0,  15, 160,   0,   0,
    128,  62, 189,  55, 134, 181,
      0,  36, 116,  73,   0,   0,
    128,  64,  31,   0,   0,   2,
      5,   0,   0, 128,   0,   0,
      3, 144,  31,   0,   0,   2,
      0,   0,   0, 144,   0,   8,
     15, 160,   1,   0,   0,   2,
      0,   0,   7, 128,   2,   0,
    228, 160,   4,   0,   0,   4,
      1,   0,  15, 128,   0,   0,
     69, 160,   0,   0,  20, 128,
      0,   0,  68, 144,  66,   0,
      0,   3,   2,   0,  15, 128,
      1,   0, 228, 128,   0,   8,
    228, 160,  66,   0,   0,   3,
      1,   0,  15, 128,   1,   0,
    238, 128,   0,   8, 228, 160,
      4,   0,   0,   4,   0,   0,
      2, 128,   2,   0,   0, 128,
      2,   0, 255, 160,   2,   0,
     85, 128,   4,   0,   0,   4,
      0,   0,   2, 128,   2,   0,
    170, 128,   2,   0, 255, 160,
      0,   0,  85, 128,   4,   0,
      0,   4,   0,   0,   8, 128,
      1,   0,   0, 128,   2,   0,
    255, 160,   1,   0,  85, 128,
      4,   0,   0,   4,   0,   0,
      8, 128,   1,   0, 170, 128,
      2,   0, 255, 160,   0,   0,
    255, 128,  11,   0,   0,   3,
      1,   0,   8, 128,   0,   0,
     85, 128,   0,   0, 255, 128,
      4,   0,   0,   4,   3,   0,
     15, 128,   0,   0,  84, 160,
      0,   0, 130, 128,   0,   0,
     68, 144,  66,   0,   0,   3,
      4,   0,  15, 128,   3,   0,
    228, 128,   0,   8, 228, 160,
     66,   0,   0,   3,   3,   0,
     15, 128,   3,   0, 238, 128,
      0,   8, 228, 160,   4,   0,
      0,   4,   0,   0,   1, 128,
      4,   0,   0, 128,   2,   0,
    255, 160,   4,   0,  85, 128,
      4,   0,   0,   4,   0,   0,
      1, 128,   4,   0, 170, 128,
      2,   0, 255, 160,   0,   0,
      0, 128,  66,   0,   0,   3,
      5,   0,  15, 128,   0,   0,
    228, 144,   0,   8, 228, 160,
      4,   0,   0,   4,   0,   0,
      4, 128,   5,   0,   0, 128,
      2,   0, 255, 160,   5,   0,
     85, 128,   4,   0,   0,   4,
      0,   0,   4, 128,   5,   0,
    170, 128,   2,   0, 255, 160,
      0,   0, 170, 128,  11,   0,
      0,   3,   2,   0,   8, 128,
      0,   0, 170, 128,   0,   0,
      0, 128,  11,   0,   0,   3,
      3,   0,   8, 128,   1,   0,
    255, 128,   2,   0, 255, 128,
      4,   0,   0,   4,   1,   0,
      8, 128,   3,   0,   0, 128,
      2,   0, 255, 160,   3,   0,
     85, 128,   4,   0,   0,   4,
      1,   0,   8, 128,   3,   0,
    170, 128,   2,   0, 255, 160,
      1,   0, 255, 128,  11,   0,
      0,   3,   2,   0,   8, 128,
      3,   0, 255, 128,   1,   0,
    255, 128,  10,   0,   0,   3,
      3,   0,   8, 128,   0,   0,
    255, 128,   0,   0,  85, 128,
      5,   0,   0,   3,   0,   0,
      8, 128,   0,   0, 255, 128,
      4,   0,   0, 160,   4,   0,
      0,   4,   0,   0,   2, 128,
      0,   0,  85, 128,   4,   0,
      0, 160,   0,   0, 255, 128,
      4,   0,   0,   4,   0,   0,
      2, 128,   0,   0,   0, 128,
      4,   0,   0, 160,   0,   0,
     85, 128,  10,   0,   0,   3,
      4,   0,   8, 128,   0,   0,
      0, 128,   0,   0, 170, 128,
     10,   0,   0,   3,   0,   0,
      1, 128,   4,   0, 255, 128,
      3,   0, 255, 128,  10,   0,
      0,   3,   3,   0,   8, 128,
      1,   0, 255, 128,   0,   0,
      0, 128,   4,   0,   0,   4,
      0,   0,   1, 128,   1,   0,
    255, 128,   4,   0,   0, 160,
      0,   0,  85, 128,   2,   0,
      0,   3,   0,   0,   1, 128,
      0,   0, 170, 129,   0,   0,
      0, 128,   2,   0,   0,   3,
      0,   0,   2, 128,   2,   0,
    255, 128,   3,   0, 255, 129,
      2,   0,   0,   3,   0,   0,
      4, 128,   0,   0,  85, 128,
      4,   0,  85, 160,   6,   0,
      0,   2,   0,   0,   2, 128,
      0,   0,  85, 128,  88,   0,
      0,   4,   0,   0,   2, 128,
      0,   0, 170, 128,   0,   0,
     85, 128,   4,   0, 170, 160,
      5,   0,   0,   3,   0,   0,
     17, 128,   0,   0,  85, 128,
      0,   0,   0, 139,   4,   0,
      0,   4,   0,   0,   1, 128,
      0,   0,   0, 128,   2,   0,
    255, 161,   2,   0,  85, 161,
     10,   0,   0,   3,   0,   0,
     14, 128,   1,   0, 144, 128,
      2,   0, 144, 128,  10,   0,
      0,   3,   6,   0,   7, 128,
      3,   0, 228, 128,   4,   0,
    228, 128,  10,   0,   0,   3,
      7,   0,   7, 128,   6,   0,
    228, 128,   0,   0, 249, 128,
     10,   0,   0,   3,   0,   0,
     14, 128,   5,   0, 144, 128,
      7,   0, 144, 128,   4,   0,
      0,   4,   6,   0,   7, 128,
      7,   0, 228, 128,   3,   0,
      0, 160,   3,   0,  85, 160,
     11,   0,   0,   3,   7,   0,
      7, 128,   2,   0, 228, 128,
      1,   0, 228, 128,   2,   0,
      0,   3,   1,   0,   7, 128,
      1,   0, 228, 128,   2,   0,
    228, 128,   2,   0,   0,   3,
      1,   0,   7, 128,   3,   0,
    228, 128,   1,   0, 228, 128,
     11,   0,   0,   3,   2,   0,
      7, 128,   4,   0, 228, 128,
      3,   0, 228, 128,   2,   0,
      0,   3,   1,   0,   7, 128,
      4,   0, 228, 128,   1,   0,
    228, 128,  11,   0,   0,   3,
      3,   0,   7, 128,   7,   0,
    228, 128,   2,   0, 228, 128,
      5,   0,   0,   3,   2,   0,
      7, 128,   3,   0, 228, 128,
      4,   0, 255, 160,  11,   0,
      0,   3,   4,   0,   7, 128,
      3,   0, 228, 128,   5,   0,
    228, 128,   2,   0,   0,   3,
      3,   0,   7, 128,   4,   0,
    228, 129,   2,   0, 170, 160,
      6,   0,   0,   2,   4,   0,
      1, 128,   2,   0,   0, 128,
      6,   0,   0,   2,   4,   0,
      2, 128,   2,   0,  85, 128,
      6,   0,   0,   2,   4,   0,
      4, 128,   2,   0, 170, 128,
      5,   0,   0,   3,   0,   0,
     14, 128,   0,   0, 228, 128,
      4,   0, 144, 128,   6,   0,
      0,   2,   2,   0,   1, 128,
      6,   0,   0, 128,   6,   0,
      0,   2,   2,   0,   2, 128,
      6,   0,  85, 128,   6,   0,
      0,   2,   2,   0,   4, 128,
      6,   0, 170, 128,   5,   0,
      0,   3,   2,   0,   7, 128,
      2,   0, 228, 128,   3,   0,
    228, 128,  11,   0,   0,   3,
      3,   0,   7, 128,   0,   0,
    249, 129,   2,   0, 228, 128,
     11,   0,   0,   3,   0,   0,
      2, 128,   3,   0,   0, 128,
      3,   0,  85, 128,  11,   0,
      0,   3,   1,   0,   8, 128,
      0,   0,  85, 128,   3,   0,
    170, 128,  10,   0,   0,   3,
      0,   0,   2, 128,   1,   0,
    255, 128,   2,   0,   0, 160,
     11,   0,   0,   3,   1,   0,
      8, 128,   3,   0, 170, 160,
      0,   0,  85, 128,   5,   0,
      0,   3,   0,   0,   2, 128,
      1,   0, 255, 128,   1,   0,
      0, 160,   5,   0,   0,   3,
      0,   0,   1, 128,   0,   0,
      0, 128,   0,   0,  85, 128,
      4,   0,   0,   4,   0,   0,
     14, 128,   0,   0,   0, 128,
      1,   0, 144, 128,   5,   0,
    144, 128,   4,   0,   0,   4,
      0,   0,   1, 128,   0,   0,
      0, 128,   3,   0,   0, 160,
      3,   0, 255, 160,   6,   0,
      0,   2,   0,   0,   1, 128,
      0,   0,   0, 128,   5,   0,
      0,   3,   0,   8,   7, 128,
      0,   0,   0, 128,   0,   0,
    249, 128,   1,   0,   0,   2,
      0,   8,   8, 128,   2,   0,
    170, 160, 255, 255,   0,   0
};
