// motion_blur_ps.h -- compiled pixel shader bytecode for Phase E of the
// visual-enhancement suite plan (approved plan,
// C:\Users\kyesa\.claude\plans\twinkly-tickling-gem.md): a camera-only
// (view-angle-delta-based) directional motion blur, the second real effect
// built on Phase A's capture/composite pipeline (DrawFullScreenPass,
// overlay_hud.cpp), composed after Phase B's RCAS sharpen when both are
// enabled (DrawFullScreenPass is called twice in sequence -- the second call's
// capture naturally picks up the first pass's already-sharpened result, no
// special multi-pass plumbing needed).
//
// Compiled OFFLINE via the Windows SDK's fxc.exe from
// re_notes/shaders/motion_blur.hlsl (source, and the full design rationale --
// this is NOT a port of any external reference, unlike fsr_rcas_ps.h -- kept
// in re_notes/ for the record, not part of the build) -- embedded directly as
// a byte array, exactly like this project's other precompiled shaders. No
// runtime shader-compiler dependency.
//
// ps_2_0 -- unlike RCAS, this simple 8-tap directional-average blur fits
// comfortably (27 instruction slots vs. the profile's 64 cap), matching this
// project's usual shader convention.
#pragma once

#if 0
//
// Generated by Microsoft (R) HLSL Shader Compiler 10.1
//
// Parameters:
//
//   float4 blurVec;
//   sampler2D tex0;
//
//
// Registers:
//
//   Name         Reg   Size
//   ------------ ----- ----
//   blurVec      c0       1
//   tex0         s0       1
//

    ps_2_0
    def c1, -0.5, -0.357142866, -0.214285702, -0.0714285374
    def c2, 0.071428597, 0.214285731, 0.357142925, 0.125
    def c3, 1, 0, 0, 0
    dcl t0.xy
    dcl_2d s0
    mov r0.xy, c0
    mad r1.xy, r0, c1.x, t0
    mad r2.xy, r0, c1.y, t0
    mad r3.xy, r0, c1.z, t0
    mad r4.xy, r0, c1.w, t0
    mad r5.xy, r0, c2.x, t0
    mad r6.xy, r0, c2.y, t0
    mad r7.xy, r0, c2.z, t0
    mad r0.xy, r0, -c1.x, t0
    texld r1, r1, s0
    texld r2, r2, s0
    texld r3, r3, s0
    texld r4, r4, s0
    texld r5, r5, s0
    texld r6, r6, s0
    texld r7, r7, s0
    texld r0, r0, s0
    add r1.xyz, r1, r2
    add r1.xyz, r3, r1
    add r1.xyz, r4, r1
    add r1.xyz, r5, r1
    add r1.xyz, r6, r1
    add r1.xyz, r7, r1
    add r0.xyz, r0, r1
    mul r0.xyz, r0, c2.w
    mov r0.w, c3.x
    mov oC0, r0

// approximately 27 instruction slots used (8 texture, 19 arithmetic)
#endif

const BYTE g_motionBlurPixelShaderBytecode[] =
{
      0,   2, 255, 255, 254, 255,
     42,   0,  67,  84,  65,  66,
     28,   0,   0,   0, 123,   0,
      0,   0,   0,   2, 255, 255,
      2,   0,   0,   0,  28,   0,
      0,   0,   0,   1,   0,   0,
    116,   0,   0,   0,  68,   0,
      0,   0,   2,   0,   0,   0,
      1,   0,   2,   0,  76,   0,
      0,   0,   0,   0,   0,   0,
     92,   0,   0,   0,   3,   0,
      0,   0,   1,   0,   2,   0,
    100,   0,   0,   0,   0,   0,
      0,   0,  98, 108, 117, 114,
     86, 101,  99,   0,   1,   0,
      3,   0,   1,   0,   4,   0,
      1,   0,   0,   0,   0,   0,
      0,   0, 116, 101, 120,  48,
      0, 171, 171, 171,   4,   0,
     12,   0,   1,   0,   1,   0,
      1,   0,   0,   0,   0,   0,
      0,   0, 112, 115,  95,  50,
     95,  48,   0,  77, 105,  99,
    114, 111, 115, 111, 102, 116,
     32,  40,  82,  41,  32,  72,
     76,  83,  76,  32,  83, 104,
     97, 100, 101, 114,  32,  67,
    111, 109, 112, 105, 108, 101,
    114,  32,  49,  48,  46,  49,
      0, 171,  81,   0,   0,   5,
      1,   0,  15, 160,   0,   0,
      0, 191, 110, 219, 182, 190,
    182, 109,  91, 190,  32,  73,
    146, 189,  81,   0,   0,   5,
      2,   0,  15, 160,  40,  73,
    146,  61, 184, 109,  91,  62,
    112, 219, 182,  62,   0,   0,
      0,  62,  81,   0,   0,   5,
      3,   0,  15, 160,   0,   0,
    128,  63,   0,   0,   0,   0,
      0,   0,   0,   0,   0,   0,
      0,   0,  31,   0,   0,   2,
      0,   0,   0, 128,   0,   0,
      3, 176,  31,   0,   0,   2,
      0,   0,   0, 144,   0,   8,
     15, 160,   1,   0,   0,   2,
      0,   0,   3, 128,   0,   0,
    228, 160,   4,   0,   0,   4,
      1,   0,   3, 128,   0,   0,
    228, 128,   1,   0,   0, 160,
      0,   0, 228, 176,   4,   0,
      0,   4,   2,   0,   3, 128,
      0,   0, 228, 128,   1,   0,
     85, 160,   0,   0, 228, 176,
      4,   0,   0,   4,   3,   0,
      3, 128,   0,   0, 228, 128,
      1,   0, 170, 160,   0,   0,
    228, 176,   4,   0,   0,   4,
      4,   0,   3, 128,   0,   0,
    228, 128,   1,   0, 255, 160,
      0,   0, 228, 176,   4,   0,
      0,   4,   5,   0,   3, 128,
      0,   0, 228, 128,   2,   0,
      0, 160,   0,   0, 228, 176,
      4,   0,   0,   4,   6,   0,
      3, 128,   0,   0, 228, 128,
      2,   0,  85, 160,   0,   0,
    228, 176,   4,   0,   0,   4,
      7,   0,   3, 128,   0,   0,
    228, 128,   2,   0, 170, 160,
      0,   0, 228, 176,   4,   0,
      0,   4,   0,   0,   3, 128,
      0,   0, 228, 128,   1,   0,
      0, 161,   0,   0, 228, 176,
     66,   0,   0,   3,   1,   0,
     15, 128,   1,   0, 228, 128,
      0,   8, 228, 160,  66,   0,
      0,   3,   2,   0,  15, 128,
      2,   0, 228, 128,   0,   8,
    228, 160,  66,   0,   0,   3,
      3,   0,  15, 128,   3,   0,
    228, 128,   0,   8, 228, 160,
     66,   0,   0,   3,   4,   0,
     15, 128,   4,   0, 228, 128,
      0,   8, 228, 160,  66,   0,
      0,   3,   5,   0,  15, 128,
      5,   0, 228, 128,   0,   8,
    228, 160,  66,   0,   0,   3,
      6,   0,  15, 128,   6,   0,
    228, 128,   0,   8, 228, 160,
     66,   0,   0,   3,   7,   0,
     15, 128,   7,   0, 228, 128,
      0,   8, 228, 160,  66,   0,
      0,   3,   0,   0,  15, 128,
      0,   0, 228, 128,   0,   8,
    228, 160,   2,   0,   0,   3,
      1,   0,   7, 128,   1,   0,
    228, 128,   2,   0, 228, 128,
      2,   0,   0,   3,   1,   0,
      7, 128,   3,   0, 228, 128,
      1,   0, 228, 128,   2,   0,
      0,   3,   1,   0,   7, 128,
      4,   0, 228, 128,   1,   0,
    228, 128,   2,   0,   0,   3,
      1,   0,   7, 128,   5,   0,
    228, 128,   1,   0, 228, 128,
      2,   0,   0,   3,   1,   0,
      7, 128,   6,   0, 228, 128,
      1,   0, 228, 128,   2,   0,
      0,   3,   1,   0,   7, 128,
      7,   0, 228, 128,   1,   0,
    228, 128,   2,   0,   0,   3,
      0,   0,   7, 128,   0,   0,
    228, 128,   1,   0, 228, 128,
      5,   0,   0,   3,   0,   0,
      7, 128,   0,   0, 228, 128,
      2,   0, 255, 160,   1,   0,
      0,   2,   0,   0,   8, 128,
      3,   0,   0, 160,   1,   0,
      0,   2,   0,   8,  15, 128,
      0,   0, 228, 128, 255, 255,
      0,   0
};
