#include "native_config_backup.h"

#include <windows.h>
#include <cstdio>
#include <cstring>

extern void LogFromController(const char* msg); // dllmain.cpp

namespace
{
    // Exe-relative path helper -- same convention as this project's own
    // texture_upscale_cache.cpp EnsureCacheDir (GetModuleFileNameA against
    // the process's own main module, not a hardcoded/CWD-relative path).
    bool BuildExeRelativePath(const char* relative, char* out, size_t outSize)
    {
        char exeDir[MAX_PATH];
        GetModuleFileNameA(nullptr, exeDir, MAX_PATH);
        char* lastSlash = strrchr(exeDir, '\\');
        if (lastSlash) *(lastSlash + 1) = '\0';
        return sprintf_s(out, static_cast<size_t>(outSize), "%s%s", exeDir, relative) > 0;
    }

    // Real, cheap corruption heuristic. config.cfg is a plain-text,
    // engine-generated file ("// generated by Infinity Ward, do not
    // modify") of `seta "key" "value"`/`bind KEY "command"` lines. A write
    // interrupted mid-line (a real crash during the native archive-to-config
    // step) leaves the file ending mid-string -- reliably detectable as an
    // ODD number of double-quote characters, since every complete line's
    // quoted portions always close in pairs, plus the file simply not ending
    // on a real line break. A minimum size check catches the same failure
    // mode even in the (unlikely) case a truncation happened to land on an
    // even quote count -- the real truncated file this fix was written
    // against was 2515 bytes against a real healthy file's several KB.
    bool LooksValid(const char* path)
    {
        FILE* f = nullptr;
        if (fopen_s(&f, path, "rb") != 0 || !f) return false;
        fseek(f, 0, SEEK_END);
        long size = ftell(f);
        if (size < 512) { fclose(f); return false; }
        fseek(f, 0, SEEK_SET);

        long quoteCount = 0;
        int c, lastChar = 0;
        while ((c = fgetc(f)) != EOF) {
            if (c == '"') ++quoteCount;
            lastChar = c;
        }
        fclose(f);

        bool endsOnLineBreak = (lastChar == '\n' || lastChar == '\r');
        return endsOnLineBreak && (quoteCount % 2 == 0);
    }
}

void BackupOrRestoreNativeConfigCfg()
{
    char configPath[MAX_PATH], backupPath[MAX_PATH];
    if (!BuildExeRelativePath("players2\\config.cfg", configPath, sizeof(configPath))) return;
    if (!BuildExeRelativePath("players2\\config.cfg.mw3ncp-backup", backupPath, sizeof(backupPath))) return;

    DWORD configAttrs = GetFileAttributesA(configPath);
    bool configExists = configAttrs != INVALID_FILE_ATTRIBUTES;

    if (configExists && !LooksValid(configPath)) {
        // Real, live-confirmed incident (2026-09-29): a native engine crash
        // left this file truncated mid-write; every subsequent launch kept
        // reading the broken file back in. Restore from our own last-known-
        // good backup if one exists.
        DWORD backupAttrs = GetFileAttributesA(backupPath);
        if (backupAttrs != INVALID_FILE_ATTRIBUTES) {
            if (CopyFileA(backupPath, configPath, FALSE)) {
                LogFromController("[config-cfg-backup] players2/config.cfg looked corrupted (truncated mid-write) -- "
                    "restored from mw3ncp-backup.");
            } else {
                char buf[300];
                sprintf_s(buf, "[config-cfg-backup] players2/config.cfg looked corrupted but restore FAILED "
                    "(CopyFileA error=%lu) -- leaving it as-is.", GetLastError());
                LogFromController(buf);
            }
        } else {
            LogFromController("[config-cfg-backup] players2/config.cfg looked corrupted (truncated mid-write) but no "
                "backup exists yet this install -- leaving it as-is (deleting it would let the engine regenerate a "
                "fresh default, but that's a real, meaningful action this project won't take without a backup to "
                "fall back on first).");
        }
        return; // Don't refresh the backup from a file we just flagged as broken (or a broken
                // file we couldn't restore) -- wait for a later, genuinely healthy launch.
    }

    if (configExists) {
        // Real, current session's config looks healthy -- refresh our own
        // backup so the NEXT corruption (if any) has a recent, real
        // known-good copy to restore from, not a stale/missing one.
        CopyFileA(configPath, backupPath, FALSE);
    }
    // If configExists is false, there's nothing to back up or restore yet --
    // the native engine will generate a fresh default this session, and a
    // LATER healthy launch will capture the first real backup.
}
